backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: simple

collections:
  - name: "products_json"
    label: "Productos (lista)"
    files:
      - file: "content/products/products.json"
        label: "Listado de productos"
        name: "products"
        fields:
          - label: "Productos"
            name: "products"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "Nombre", name: "title", widget: "string" }
              - { label: "Descripción corta", name: "subtitle", widget: "string", required: false }
              - { label: "Imagen (cuadrada)", name: "image", widget: "image" }
              - { label: "Enlace de compra", name: "buy_url", widget: "string", required: false }
              - { label: "Por qué lo recomiendo", name: "why", widget: "text", required: false }
              - { label: "Valoración (1-5)", name: "rating", widget: "number", min: 1, max: 5, required: false }