backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

locale: "es"

collections:
  - name: "productos"
    label: "Productos"
    label_singular: "Producto"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Descripción corta (máx 90)", name: "short", widget: "string" }
      - { label: "Por qué lo recomiendo (máx 250)", name: "why", widget: "text" }
      - { label: "Valoración (1–5)", name: "rating", widget: "number", min: 1, max: 5, step: 0.5, default: 5 }
      - { label: "Imagen (cuadrada 1080×1080)", name: "image", widget: "image" }
      - { label: "URL Comprar en Amazon", name: "amazon_url", widget: "string" }
      - { label: "Producto destacado (Carrusel 5★)", name: "featured", widget: "boolean", default: false }
      - { label: "Categoría", name: "category", widget: "select", options: ["reformas", "hogar", "3D", "tecnologia", "otros"], default: "reformas" }
      - { label: "Publicado", name: "published", widget: "boolean", default: true }
