bbackend:
  name: github
  repo: generacion-o2/RecomendacionesGo2_v3.3.7
  branch: main
  base_url: https://recomendaciones.generacion-o2.org
  auth_endpoint: /api/auth
  publish_mode: editorial_workflow
  
media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "products"
    label: "Productos"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Herramientas", "Hogar", "Tecnología"] }
      - { label: "Imagen principal (cuadrada 800x800)", name: "image", widget: "image", allow_multiple: false }
      - { label: "Resumen (máx 250 caracteres)", name: "summary", widget: "text", max_length: 250 }
      - { label: "Enlace de compra (Amazon)", name: "buy_url", widget: "string" }
      - { label: "Por qué lo recomiendo (ampliado)", name: "why", widget: "markdown", required: false }
      - label: "Puntuación"
        name: "rating"
        widget: "number"
        value_type: "float"
        min: 4
        max: 5
        step: 0.1
        default: 4.5
        required: true
      - { label: "Destacado", name: "featured", widget: "boolean", default: false }
      - { label: "Borrador (ocultar del listado)", name: "draft", widget: "boolean", default: false }
