backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: simple

collections:
  - name: "products"
    label: "Productos"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Herramientas", "Hogar", "Tecnología"] }
      - { label: "Imagen principal (cuadrada 800x800)", name: "image", widget: "image", allow_multiple: false }
      - { label: "Resumen (máx 250 caracteres)", name: "summary", widget: "text", max_length: 250 }
      - { label: "Enlace de compra (Amazon)", name: "buy_url", widget: "string" }
      - { label: "Por qué lo recomiendo (ampliado)", name: "why", widget: "markdown", required: false }
      - { label: "Puntuación", name: "rating", widget: "number", min: 4.0, max: 5.0, step: 0.1, default: 4.5 }
      - { label: "Destacado", name: "featured", widget: "boolean", default: false }
      - { label: "Borrador (ocultar del listado)", name: "draft", widget: "boolean", default: false }
