backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: simple

collections:
  - name: "products"
    label: "Productos"
    label_singular: "Producto"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Reformas", "3D", "Electrodomésticos", "Herramientas", "Hogar", "Tecnología", "Otros"], default: "Herramientas" }
      - { label: "Imagen principal (cuadrada 800×800)", name: "image", widget: "image", allow_multiple: false, hint: "Sube imagen cuadrada (800×800 recomendado)." }
      - label: "Resumen (máx 250 caracteres)"
        name: "summary"
        widget: "text"
        hint: "Texto corto que se mostrará como 'por qué lo recomiendo' (máx 250)."
        pattern: ["^.{0,250}$", "Hasta 250 caracteres"]
      - { label: "Enlace de compra (Amazon)", name: "buy_url", widget: "string", hint: "Pega aquí tu enlace completo o corto (amzn.to…)" }
      - { label: "Por qué lo recomiendo (ampliado)", name: "why", widget: "markdown", required: false }
      - { label: "Valoración (4.0–5.0)", name: "rating", widget: "number", value_type: "float", min: 4, max: 5, step: 0.1, default: 4.5 }
      - { label: "Destacado (aparece en 'Producto destacado')", name: "featured", widget: "boolean", default: false }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
